# Generated by Django 4.1.2 on 2022-10-05 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('LinkedIn', 'Linkedin'), ('Github', 'Github')], max_length=9)),
                ('username', models.CharField(max_length=305)),
                ('url', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolodex.contact')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cellular', 'Cell'), ('Work', 'Work'), ('Home', 'Home'), ('Business', 'Business'), ('Office', 'Office')], max_length=8)),
                ('number', models.CharField(max_length=26)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolodex.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolodex.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Business', 'Business'), ('Support', 'Support')], max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolodex.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line1', models.CharField(max_length=1024)),
                ('line2', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('line3', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('city', models.CharField(max_length=50)),
                ('zip_or_post_code', models.CharField(max_length=12)),
                ('state_province_county', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=3)),
                ('other_address_details', models.TextField(blank=True, default=None, null=True)),
                ('contacts', models.ManyToManyField(to='rolodex.contact')),
            ],
        ),
    ]
